default: &default
  adapter: postgresql
  encoding: unicode
  username: jose
  password: senha123
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bancoze_development

test:
  <<: *default
  database: bancoze_test

production:
  primary:
    <<: *default
    database: bancoze_development